name: Tests

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  test:
    name: run tests
    runs-on: golang:1.17-alpine3.15

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: tests
        run: go test -v ./... -cover
